Repository SlvCtrlPlus/slvctrlplus-server, pull requests merged in 2024-02, with the labels that each got.

#29 Switch to new dic
  package.json
  src/device/provider/deviceProviderFactory.ts
  src/index.ts
  src/serviceMap.ts
  src/serviceProvider/automationServiceProvider.ts
  src/serviceProvider/controllerServiceProvider.ts
  src/serviceProvider/deviceServiceProvider.ts
  src/serviceProvider/factoryServiceProvider.ts
  src/serviceProvider/loggerServiceProvider.ts
  src/serviceProvider/repositoryServiceProvider.ts
  src/serviceProvider/serializationServiceProvider.ts
  src/serviceProvider/serverServiceProvider.ts
  src/serviceProvider/settingsServiceProvider.ts
  src/serviceProvider/socketServiceProvider.ts
  src/settings/deviceSource.ts
  src/settings/knownDevice.ts
  yarn.lock
Labels: enhancement

#30 Remove wrongly added imports
  src/device/provider/deviceProviderFactory.ts
  src/settings/deviceSource.ts
  src/settings/knownDevice.ts
Labels: patch

#27 Adapt to missing scan and id persistence features in intiface-engine
  src/device/protocol/buttplugIo/buttplugIoDeviceFactory.ts
  src/device/protocol/buttplugIo/buttplugIoWebsocketDeviceProvider.ts
  src/device/protocol/buttplugIo/buttplugIoWebsocketDeviceProviderFactory.ts
Labels: enhancement, minor

#32 Use pull_request_target instead of just pull_request
  .github/workflows/release.yml
Labels: bug, minor
